import type { SiteContent } from "./types";

// Seed content — the data that previously lived hardcoded inside the section
// components. Served whenever no content.json exists in Blob storage (e.g.
// local dev without a BLOB_READ_WRITE_TOKEN), and used to seed the first save.

export const DEFAULT_CONTENT: SiteContent = {
  projects: [
    {
      id: "karyaai",
      name: "KaryaAI",
      tag: "MERN Stack · Productivity",
      description: "Task manager with JWT auth, MongoDB syncing, and AI-powered task sorting.",
      tech: ["React", "Node.js", "MongoDB", "Express", "Tailwind"],
      github: "https://github.com/RavangDai/SmartTodo",
      live: "https://karyaai.vercel.app/",
      year: 2026,
      status: "Completed",
      image: "/KaryaAI.png",
      video: "https://youtu.be/sQ7IdpM0jQg",
    },
    {
      id: "crumbcraft",
      name: "CrumbCraft",
      tag: "Full-stack · AI · Productivity",
      description:
        "Two AI-powered dev tools in one: Crumb compresses messy conversations into structured docs, Craft helps engineer precise AI prompts with guided templates.",
      tech: ["Next.js", "React", "Tailwind CSS", "Gemini 2.5", "Framer Motion"],
      github: "https://github.com/RavangDai/crumb",
      live: "https://crumbcrraft.vercel.app/",
      year: 2026,
      status: "Completed",
      image: "/CrumbCraft.png",
    },
    {
      id: "revveal",
      name: "Revveal",
      tag: "Full-stack · AI · Data",
      description:
        "Finds underpriced used cars before everyone else. An async Celery + Redis pipeline scrapes marketplaces, predicts fair market price, and ranks listings by discount, behind JWT auth and rate-limited APIs.",
      tech: ["FastAPI", "React", "PostgreSQL", "Celery", "Redis", "Docker"],
      github: "https://github.com/RavangDai/car-deal",
      year: 2026,
      status: "In progress",
      image: "/revveal.png",
    },
    {
      id: "vectorvance",
      name: "VectorVance",
      tag: "Raspberry Pi · Computer Vision · Robotics",
      description:
        "Autonomous car on Raspberry Pi that follows lanes, detects obstacles and traffic signs via SSD MobileNet, navigates colour-coded forks, and streams live telemetry to a web dashboard.",
      tech: ["Python", "OpenCV", "Flask", "Raspberry Pi", "SSD MobileNet", "PID Control", "NumPy", "lgpio"],
      github: "https://github.com/RavangDai/VectorVance",
      year: 2025,
      status: "Completed",
      image: "/vvdash.png",
    },
    {
      id: "buzzboard",
      name: "BuzzBoard",
      tag: "Node.js · Express · MongoDB",
      description:
        "Message board app with topic subscriptions, recent-message dashboard, posting, stats, and MVC, Observer, and Singleton pattern implementations over MongoDB.",
      tech: ["Node.js", "Express", "MongoDB", "Mongoose", "Handlebars", "bcryptjs", "express-session", "MVC", "Observer", "Singleton"],
      github: "https://github.com/RavangDai/Buzzboard",
      live: "https://buzzboard-fk7m.onrender.com/auth/login",
      year: 2026,
      status: "Completed",
      image: "/BuzzBoard.png",
    },
  ],

  certificates: [
    {
      id: "hackerrank-software-engineer",
      title: "Software Engineer Certificate",
      issuer: "HackerRank",
      year: 2025,
      category: "Full-stack Engineering",
      summary: "Role certification covering problem solving, REST APIs, full-stack structure, and data structures.",
      skills: ["Problem Solving", "REST APIs", "Full-stack", "Data Structures"],
      image: "/certificates/software-engineer-crop.png",
      url: "https://www.hackerrank.com/certificates/iframe/1ec7df9efdd8",
      icon: "Code2",
      featured: true,
    },
    {
      id: "hackerrank-sql-advanced",
      title: "SQL (Advanced) Certificate",
      issuer: "HackerRank",
      year: 2025,
      category: "Data / Backend",
      summary: "Advanced SQL certification covering query optimization, indexing, joins, subqueries, and pivots.",
      skills: ["Complex Queries", "Indexing", "Joins", "Performance"],
      image: "/certificates/sql-advanced-crop.png",
      url: "https://www.hackerrank.com/certificates/a0f6fb1fb4af",
      icon: "Database",
    },
    {
      id: "simplilearn-tableau",
      title: "Introduction to Tableau",
      issuer: "Simplilearn · SkillUp",
      year: 2025,
      category: "Data Visualization",
      summary: "Completion course covering interactive dashboards, charts, and visual analytics workflows in Tableau.",
      skills: ["Tableau", "Data Visualization", "Dashboards", "Analytics"],
      image: "/tablue certificate.png",
      url: "https://www.simplilearn.com/skillup-certificate-landing?token=eyJjb3Vyc2VfaWQiOiI0MDY4IiwiY2VydGlmaWNhdGVfdXJsIjoiaHR0cHM6XC9cL2NlcnRpZmljYXRlcy5zaW1wbGljZG4ubmV0XC9zaGFyZVwvODAyNTU5NV84MzQyNzMxMTc0MTY2MzI1OTE1OC5wbmciLCJ1c2VybmFtZSI6IkJpYmVrIFBhdGhhayJ9&referrer=https%3A%2F%2Flms.simplilearn.com%2Fcourses%2F7062%2FIntroduction-to-Tableau%2Fcertificate%2Fdownload-skillup&%24web_only=true",
      icon: "BarChart3",
    },
    {
      id: "cfi-excel-finance",
      title: "Excel Fundamentals - Finance",
      issuer: "Corporate Finance Institute",
      year: 2024,
      category: "Finance & Analysis",
      summary: "Finance-focused Excel credential covering formulas, analysis workflows, and structured spreadsheet modeling.",
      skills: ["Excel Formulas", "Financial Modeling", "Data Analysis", "Pivot Tables"],
      image: "/certificates/excel-finance-crop.png",
      url: "https://credentials.corporatefinanceinstitute.com/88b6efc3-2491-4e1d-9e12-433819361baa",
      icon: "Table2",
    },
  ],

  achievements: [
    {
      id: "hacklions-2026",
      date: "Apr 2026",
      title: "1st Place · HackLions 2026",
      org: "SELU 1st Hackathon",
      category: "Competition",
      desc: "Won SELU's hackathon by building DollarPilot, a finance app that makes money management fun and brutal, shipped from zero in 6 hours.",
      icon: "Trophy",
      highlight: true,
      url: "https://devpost.com/software/dollarpilot",
    },
    {
      id: "honors-scholarship",
      date: "Fall 2024",
      title: "Honors Scholarship",
      org: "Southeastern Louisiana University",
      category: "Academic",
      desc: "Awarded the Honors Scholarship at Southeastern Louisiana University in recognition of outstanding academic achievement and potential.",
      icon: "Star",
    },
    {
      id: "hackerrank-se-cert",
      date: "2025",
      title: "Software Engineer Certificate",
      org: "HackerRank",
      category: "Certification",
      desc: "Demonstrated expertise in problem-solving, REST API design, full-stack architecture, and data structures.",
      icon: "Code2",
      url: "https://www.hackerrank.com/certificates/iframe/1ec7df9efdd8",
    },
    {
      id: "hackerrank-sql-cert",
      date: "2025",
      title: "SQL (Advanced) Certificate",
      org: "HackerRank",
      category: "Certification",
      desc: "Validated advanced SQL skills including complex queries, joins, subqueries, indexing, and performance tuning.",
      icon: "Zap",
      url: "https://www.hackerrank.com/certificates/a0f6fb1fb4af",
    },
    {
      id: "cfi-excel-cert",
      date: "2024",
      title: "Excel Fundamentals – Finance",
      org: "Corporate Finance Institute®",
      category: "Certification",
      desc: "Completed CFI's program covering financial modeling, pivot tables, Excel formulas, and data analysis for finance.",
      icon: "BookOpen",
      url: "https://credentials.corporatefinanceinstitute.com/88b6efc3-2491-4e1d-9e12-433819361baa",
    },
  ],

  stats: [
    { value: "10+", label: "Projects Shipped" },
    { value: "3.5+", label: "GPA" },
    { value: "1/1", label: "Hackathon Win Rate" },
    { value: "3", label: "Certifications" },
  ],

  site: {
    heroLine1: "Full-Stack Builder",
    heroLine2: "AI / ML Developer",
    builderLine1: "10+ shipped projects across full-stack web,",
    builderLine2: "applied AI, and computer vision.",
    email: "drbibekg2029@gmail.com",
    githubUrl: "https://github.com/RavangDai",
    linkedinUrl: "https://www.linkedin.com/in/bibek-pathak-10398a301/",
    resumeUrl: "/Bibek_Pathak_Resume_Mar26.pdf",
  },
};
